name: neural_effect
description: "A Flutter widget for an animated 3D particle background effect."
version: 1.0.2
homepage: "https://github.com/JackHars/neural_effect"

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter: